"""Regenerate STATISTICS.md from the repository itself.

    python3 scripts/statistics.py            # rewrite it
    python3 scripts/statistics.py --check    # fail if it is stale

Every figure in that document is a count of something in this repository or a
value read out of a committed result. None is typed by hand, because a hand-
typed count is correct on the day it is written and wrong on every day after.
`--check` runs in CI for the same reason the claims audit does.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "STATISTICS.md"
DEFECT_LEDGER = ROOT / "testlogs/defects.json"

# The one place the defect tally lives. It used to be typed into the template
# below *and* into the README, which is how STATISTICS.md came to say thirty-one
# while the README said thirty-five — both written truthfully, months apart.
# `audit_claims.py` now checks the README against this ledger.
DEFECTS: tuple[tuple[str, int], ...] = (
    ("Load and stress testing", 12),
    ("Deterministic simulation", 4),
    ("A security review of that work", 5),
    ("A correctness review of it", 10),
    ("Racing Qdrant's engine against this node's own index", 3),
    ("Asking what a dying link should carry first", 1),
    ("A review pass over all of that", 10),
)
WORDS = {31: "Thirty-one", 32: "Thirty-two", 33: "Thirty-three", 34: "Thirty-four",
         35: "Thirty-five", 36: "Thirty-six", 37: "Thirty-seven", 38: "Thirty-eight",
         39: "Thirty-nine", 40: "Forty", 41: "Forty-one", 42: "Forty-two",
         43: "Forty-three", 44: "Forty-four", 45: "Forty-five", 46: "Forty-six"}
O, R, B, D, G = "\033[38;5;208m", "\033[0m", "\033[1m", "\033[2m", "\033[32m"


def count(command: str) -> int:
    result = subprocess.run(command, shell=True, cwd=ROOT,
                            capture_output=True, text=True)
    return int(result.stdout.strip() or 0)


def tests() -> int:
    """How many tests there are, by asking pytest rather than by counting `def`.

    A `def test_` count is wrong the moment anyone parametrises anything, and
    this suite does.
    """
    result = subprocess.run([sys.executable, "-m", "pytest", "--collect-only", "-q"],
                            cwd=ROOT / "backend", capture_output=True, text=True)
    for line in reversed(result.stdout.splitlines()):
        if "test" in line and "collected" in line:
            return int(line.split()[0])
    return sum(1 for line in result.stdout.splitlines() if "::" in line)


def render() -> str:
    sweep = json.loads((ROOT / "testlogs/simulation.json").read_text())
    control = json.loads((ROOT / "testlogs/simulation_unsigned.json").read_text())

    modules = count("find backend/aegis -name '*.py' ! -name '__init__.py' | wc -l")
    code = count("find backend/aegis -name '*.py' -exec cat {} + | wc -l")
    test_files = count("ls backend/tests/test_*.py | wc -l")
    test_code = count("cat backend/tests/test_*.py | wc -l")
    scripts = count("ls backend/scripts/*.py | wc -l")
    script_code = count("cat backend/scripts/*.py | wc -l")
    frontend = count("cat frontend/*.js frontend/*.css frontend/*.html | wc -l")
    documentation = count("cat README.md docs/*.md backend/README.md | wc -l")
    commits = count("git rev-list --count HEAD")
    suite = tests()
    defect_rows = "\n".join(f"| {name} | {n} |" for name, n in DEFECTS)
    defect_total = sum(n for _, n in DEFECTS)

    return f"""# Project statistics

Generated by `python3 backend/scripts/statistics.py` from the repository
itself, so these cannot drift from it. Every figure is a count of something
here or a value read out of a committed result. CI fails if this file is
stale.

## Code

| | |
|---|---:|
| Modules in `backend/aegis` | {modules} |
| Lines of node code | {code:,} |
| Test files | {test_files} |
| Lines of test code | {test_code:,} |
| Tests | {suite} |
| Harnesses and tools in `backend/scripts` | {scripts} |
| Lines of harness code | {script_code:,} |
| Frontend — HTML, CSS and JS, no build step | {frontend:,} |
| Lines of documentation | {documentation:,} |
| Commits | {commits} |

Test code is about {round(test_code / code * 100)}% the size of the code it
tests. That is not a target; it is what happened when every defect had to
arrive with the test that would have caught it.

## Evidence

| | |
|---|---:|
| Deterministic executions, signed | {sweep['executions']:,} |
| Invariant failures in those | **{len(sweep['failures'])}** |
| Simulated fleet-time | {sweep['simulated_seconds'] / 86400:,.1f} days |
| Operations exchanged | {sweep['operations']:,} |
| Deterministic executions, unsigned control | {control['executions']:,} |
| Invariant failures in those | **{len(control['failures'])}** |

The control is the point. A sweep that finds nothing means nothing without a
run, on the same seeds with the same attacks, that finds something.

## Defects

| Found by | Count |
|---|---:|
{defect_rows}
| **Total, each with a regression test** | **{defect_total}** |

Four remain open and are described in the README rather than closed quietly:
an unexplained ~25 KB per memory, a ~2.8 KB/query growth with a one-variable
reproducer, ingest decay with corpus size, and operation-log compaction that
was measured, priced at about seven per cent, and judged a bad trade.

## What runs on every push

- The full test suite
- The determinism lint — no simulated module may read the clock or the
  generator directly
- The documentation claims audit — every measured number checked against the
  artefact that produced it
- This file, checked for staleness
- A signed sweep, expected to find nothing
- An unsigned control, which **fails the build if it comes back clean**
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if STATISTICS.md is out of date")
    args = parser.parse_args()

    fresh = render()
    total = sum(n for _, n in DEFECTS)
    ledger = {"total": total, "word": WORDS.get(total, str(total)),
              "by_source": {name: n for name, n in DEFECTS}}
    if not args.check:
        TARGET.write_text(fresh, encoding="utf-8")
        DEFECT_LEDGER.write_text(json.dumps(ledger, indent=2) + "\n", encoding="utf-8")
        print(f"{G}wrote{R} {TARGET.relative_to(ROOT)} and "
              f"{DEFECT_LEDGER.relative_to(ROOT)}")
        return 0
    committed = (json.loads(DEFECT_LEDGER.read_text()) if DEFECT_LEDGER.exists() else None)
    if committed != ledger:
        print(f"{O}{B}testlogs/defects.json is stale.{R} Run "
              f"{B}python3 backend/scripts/statistics.py{R} and commit the result.")
        return 1

    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if current == fresh:
        print(f"{D}STATISTICS.md matches the repository.{R}")
        return 0
    print(f"{O}{B}STATISTICS.md is stale.{R} Run "
          f"{B}python3 backend/scripts/statistics.py{R} and commit the result.")
    import difflib
    diff = difflib.unified_diff(current.splitlines(), fresh.splitlines(),
                                "committed", "regenerated", lineterm="", n=0)
    for line in list(diff)[:24]:
        print(f"  {line}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
